export const options = [
    { label: "합판재", value: "합판재"},
    { label: "MDF", value: "MDF"},
    { label: "각재", value: "각재"},
    { label: "OSB/PB", value: "OSB/PB" },
    { label: "구조재", value: "구조재" },
    { label: "사이딩재", value: "사이딩재" },
    { label: "계단재", value: "계단재" },
    { label: "라티스", value: "라티스" },
    { label: "가구재", value: "가구재" },
    { label: "목봉 (다양한 수종)", value: "목봉 (다양한 수종)" },
    { label: "방부목", value: "방부목" },
    { label: "천연데크", value: "천연데크" },
    { label: "합성데크", value: "합성데크" },
    { label: "플로어링", value: "플로어링" },
    { label: "원목/특수목 수종설명", value: "원목/특수목 수종설명" },
    { label: "원목 주문제 가공 (도면가공)", value: "원목 주문제 가공 (도면가공)" },
    { label: "조경목 /벤치재/울타리가공", value: "조경목 /벤치재/울타리가공" },
    { label: "탄화목&열처리목", value: "탄화목&열처리목" },
    { label: "우드슬랩전시장", value: "우드슬랩전시장" },
    { label: "광폭/중폭", value: "광폭/중폭" },
    { label: "소폭", value: "소폭" },
    { label: "도마/선반재", value: "도마/선반재" },
    { label: "철&주물다리", value: "철&주물다리" },
    { label: "가구재 도장제품", value: "가구재 도장제품" },
    { label: "인더스트리얼", value: "인더스트리얼" },
    { label: "제작가구", value: "제작가구" },
    { label: "블랙러스틱가구", value: "블랙러스틱가구" },
    { label: "조명", value: "조명" },
    { label: "아트타일", value: "아트타일" },
    { label: "포인트타일", value: "포인트타일" },
    { label: "콘크리트디자인블럭", value: "콘크리트디자인블럭" },
    { label: "인테리어소품", value: "인테리어소품" },
    { label: "석고보드", value: "석고보드" },
    { label: "CRC보드/콘보드", value: "CRC보드/콘보드" },
    { label: "천장재 (텍스/마이톤外)", value: "천장재 (텍스/마이톤外)" },
    { label: "내장기본재/마감재", value: "내장기본재/마감재" },
    { label: "외장마감재", value: "외장마감재" },
    { label: "경량철골", value: "경량철골" },
    { label: "경량부속", value: "경량부속" },
    { label: "단열/흡음/차음재", value: "단열/흡음/차음재" },
    { label: "시멘트/벽돌/미장방수제", value: "시멘트/벽돌/미장방수제" },
    { label: "도어문틀/몰딩/템바보드", value: "도어문틀/몰딩/템바보드" },
    { label: "바니쉬/스테인/도장도구", value: "바니쉬/스테인/도장도구" },
    { label: "타카/철물/본드", value: "타카/철물/본드" }
];