export const categoryOptionsForSelection = [
    { label: "각재", value: "각재"},
    { label: "구조재", value: "구조재" },
    { label: "사이딩재", value: "사이딩재" },
    { label: "계단재", value: "계단재" },
    { label: "바닥재", value: "바닥재" },
    { label: "원목/특수목", value: "원목/특수목" },
    { label: "조경", value: "조경" },
    { label: "제작가구", value: "제작가구" },
    { label: "조명", value: "조명" },
    { label: "타일", value: "타일" },
    { label: "인테리어소품", value: "인테리어소품" },
    { label: "석고보드", value: "석고보드" },
    { label: "천장재", value: "천장재" },
    { label: "내장기본재/마감재", value: "내장기본재/마감재" },
    { label: "외장마감재", value: "외장마감재" },
    { label: "단열/흡음/차음재", value: "단열/흡음/차음재" },
];

export const categoryOptions = [
    "각재",
    "구조재",
    "사이딩재",
    "계단재",
    "원목/특수목",
    "조경",
    "제작가구",
    "조명",
    "타일",
    "인테리어소품",
    "석고보드",
    "천장재",
    "내장기본재/마감재",
    "외장마감재",
    "단열/흡음/차음재"
];

export const amountUnitOptions = [
    { label: "㎡", value: "m2"},
    { label: "m", value: "m"},
    { label: "mm", value: "mm"},
    { label: "kg", value: "kg"},
    { label: "ea", value: "ea"},
    { label: "set", value: "set"},
    { label: "box", value: "box"},
    { label: "식", value: "식"},
    { label: "자", value: "자"},
    { label: "인", value: "인"},
    { label: "대", value: "대"},
    { label: "평", value: "평"},
    { label: "평형", value: "평형"},
];
