name: Front Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      # 레포지토리에 접근하여 CI서버로 코드를 내려받는 과정입니다.
      - name: checkout Github Action
        uses: actions/checkout@v3
      
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: install npm dependencies
        run: npm install
        
      - name: react build
        run: npm run build

      - name:  execute remote ssh & deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop $(docker ps -q --filter ancestor=interior-jung-front) # 현재 "interior-jung-front"로 실행중인 컨테이너 정지
            docker rmi $(docker images --format "{{.ID}}" interior-jung-front:latest) # 현재 "interior-jung-front"로 존재하는 도커 이미지 삭제
            cd /home/twj
            rm -rf interior-front # 업데이트 전 프로젝트 제거
            git clone https://github.com/Taewoongjung/interior-front.git # 업데이트 된 프로젝트 다시 clone
            cd /home/twj/interior-front # 업데이트 된 프로젝트로 가기
            docker build -t interior-jung-front . # Dockerfile 을 바탕으로 도커 이미지 생성
            docker run -d -p ${{ secrets.DOCKER_IMAGE_PORT }} interior-jung-front # 업데이트 된 이미지 실행
