name: Front Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      # 레포지토리에 접근하여 CI서버로 코드를 내려받는 과정입니다.
      - name: checkout Github Action
        uses: actions/checkout@v3
      
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
#      - name: install npm dependencies
#        run: npm install
#
#      - name: react build
#        run: npm run build

      - name:  execute remote ssh & deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            whoami
            ls -al
            docker kill $(docker ps -q --filter ancestor=interior-jung-front)
            docker rmi -f $(docker images --format "{{.ID}}" interior-jung-front:latest)
            cd /home/twj
            rm -rf interior-front
            git clone https://github.com/Taewoongjung/interior-front.git
            cd /home/twj/interior-front
            docker build -t interior-jung-front .
            docker run -d -p ${{ secrets.DOCKER_IMAGE_PORT }} interior-jung-front
